### ISSUE TITLE
Get issue in Deployment target14->  Cannot convert value of type 'Void?' to closure result type '()'

### ISSUE THREAD

**Issue by ParagDevac** [cs4alhaider/SearchView#1]
Hello , 
   i am getting issue while building the project . My deployment target is 14.1 . Thank you.

![Screenshot 2022-01-25 at 12 01 30 PM](https://user-images.githubusercontent.com/76836391/150923306-fd0786d8-4da6-45c4-aa96-6ce256970c31.png)

**Comment by cs4alhaider** [comment]
code refactored
